version: '3'

services:
  
  rabbitmq:
    image: rabbitmq:management
    command: rabbitmq-server
    ports:
      - 15672:15672
    expose:
      - 5672
      - 15672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
      
  gateway:
    build: nt-sc-gw
    image: erick/gateway
    ports:
      - 9090:9090
      
  ms1:
    build: nt-sc-ms1
    image: erick/ms1
    
  ms2:
    build: nt-sc-ms2
    image: erick/ms2
    devices:
        - "/dev/snd/:/dev/snd/"
    