server:
  port: 9090
---
spring:
  cloud:
    gateway:
      default-filters:
      - name: SCGWGlobalFilter
      routes:
        - id: nt-ms1
          uri: http://localhost:9091/
          predicates:
            - Path=/nt-ms1/**
          filters:
          - name: SCGWPreFilter
          - name: SCGWPostFilter
        - id: nt-ms2
          uri: http://localhost:9092/
          predicates:
            - Path=/nt-ms2/**